#!/bin/bash

set -e

SCRIPT_DIR=$( cd "$( dirname "$0" )" && pwd )
JAR_PATH="$SCRIPT_DIR/cloudgene.jar"

JAVA_ARGS="-Xmx10G"
if [ "$1" = "debug" ]; then
    shift;
    JAVA_ARGS="${JAVA_ARGS} -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=127.0.0.1:8000"
fi

java $JAVA_ARGS -jar "$JAR_PATH" "$@"
