name: Create Release

on:
  push:
    tags:
    - 'v*-statgen.*'

jobs:
  build:
    if: false

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Build Cloudgene3
      run: mvn clean install -B

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "target/cloudgene-*.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
